// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBwGlViVXSStIvn1sF6t1SeSGqEZP8u2c',
    appId: '1:59680793432:web:03e6601dbadb8205a2fb2d',
    messagingSenderId: '59680793432',
    projectId: 'lost-and-found-555',
    authDomain: 'lost-and-found-555.firebaseapp.com',
    storageBucket: 'lost-and-found-555.firebasestorage.app',
    measurementId: 'G-B2C2X980E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBimbzbMckG86WCDdo5tuGMtjAeX-csjN4',
    appId: '1:59680793432:android:792f169614c60512a2fb2d',
    messagingSenderId: '59680793432',
    projectId: 'lost-and-found-555',
    storageBucket: 'lost-and-found-555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7FahwT-8BZUM9bkse8j5y0XthugZvw0Q',
    appId: '1:59680793432:ios:f85404f1be93ac5fa2fb2d',
    messagingSenderId: '59680793432',
    projectId: 'lost-and-found-555',
    storageBucket: 'lost-and-found-555.firebasestorage.app',
    iosBundleId: 'com.example.lf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7FahwT-8BZUM9bkse8j5y0XthugZvw0Q',
    appId: '1:59680793432:ios:f85404f1be93ac5fa2fb2d',
    messagingSenderId: '59680793432',
    projectId: 'lost-and-found-555',
    storageBucket: 'lost-and-found-555.firebasestorage.app',
    iosBundleId: 'com.example.lf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBwGlViVXSStIvn1sF6t1SeSGqEZP8u2c',
    appId: '1:59680793432:web:4b07786e3ab599d7a2fb2d',
    messagingSenderId: '59680793432',
    projectId: 'lost-and-found-555',
    authDomain: 'lost-and-found-555.firebaseapp.com',
    storageBucket: 'lost-and-found-555.firebasestorage.app',
    measurementId: 'G-9GNBD3XC9Z',
  );

}